chore: update ci

diff --git a/.github/workflows/catalogs-cd.yml b/.github/workflows/catalogs-cd.yml
--- a/.github/workflows/catalogs-cd.yml
+++ b/.github/workflows/catalogs-cd.yml
@@ -71,7 +71,7 @@ jobs:
          !(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, 'chore') || contains(github.event.head_commit.message, 'docs') || contains(github.event.head_commit.message, 'style')) &&
           github.actor != 'dependabot[bot]' &&
           contains(fromJson('["develop", "main", "preview", "beta", "devops/ci"]'), github.ref_name) &&
-         ((github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch')
+          ((github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event != 'pull_request') || github.event_name == 'workflow_dispatch')
 
     # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
     # Job outputs containing expressions are evaluated on the runner at the end of each job
@@ -79,19 +79,17 @@ jobs:
       environment-name: ${{ steps.environment-name-step.outputs.environment-name }}
 
     steps:
-
       - name: Job Info
         run: |
           echo "pre-check is successful."
           echo "branch is: ${{ github.ref_name }}"
           echo workspace is: ${{ github.workspace }}
           echo "is workflow_dispatch event? ${{ github.event_name == 'workflow_dispatch' }}"
-          echo "is push event? ${{ github.event_name == 'push' }}"
-          echo "is pull request event? ${{ github.event_name == 'pull_request' }}"
+          echo "is workflow_run event? ${{ github.event_name == 'workflow_run' }}"
 
       - name: Print Triggered Workflow Information
         run: |
-          echo ${{ toJSON(github.event.workflow_run) }}
+          echo "${{ toJSON(github.event.workflow_run) }}"
           echo "Triggering Workflow ID: ${{ github.event.workflow_run.id }}"
           echo "Triggering Workflow Name: ${{ github.event.workflow_run.workflow_id }}"
           echo "Triggering Workflow Run Number: ${{ github.event.workflow_run.run_number }}"
@@ -157,6 +155,7 @@ jobs:
       registry: ${{ vars.DOCKER_REGISTRY }} # ghcr.io
       registry-endpoint: ${{ github.repository }}
 
+  # when we use needs for job if previous job skipped like `call-build-test-push` our job will be skipped but we can use always() to run in all situation also when previous job skipped
   workflow-info:
     runs-on: ubuntu-latest
     needs: [pre-check, call-build-test-push]
@@ -166,6 +165,7 @@ jobs:
     # https://docs.github.com/en/actions/learn-github-actions/expressions#operators
     if: |
       always() &&
+      (needs.pre-check.result == 'success') &&
       (needs.call-build-test-push.result == 'success' || needs.call-build-test-push.result == 'skipped') &&
       ((github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch')
 
@@ -201,15 +201,20 @@ jobs:
         if: success()
         run: ls -R "${{ github.workspace }}/artifacts"
 
-      # https://askubuntu.com/questions/86849/how-to-unzip-a-zip-file-from-the-terminal
-      - name: unzip artifacts
+      - name: Get CD Status
         if: success()
+        id: cd-status-step
         run: |
-          unzip "artifacts/${{ vars.CATALOGS_SERVICE_NAME }}_test_artifacts/test-results.zip" -d "output"
-
-      - name: Ls Output Files
-        if: success()
-        run: ls -R ${{ github.workspace }}/output
+          CD_STATUS_FILE="artifacts/${{ vars.CATALOGS_SERVICE_NAME }}_cd_status_artifacts/cd_status.txt"
+          if [ -f $CD_STATUS_FILE ]; then
+             CD_STATUS=$(cat $CD_STATUS_FILE)
+             echo "cd-status=$CD_STATUS" >> "$GITHUB_OUTPUT"
+             if [ $CD_STATUS != 'true' ]; then
+                exit 1
+          else
+             echo "Error: CD_STATUS_FILE not found."
+             exit 1
+          fi
 
       - name: Get CI Application Version
         if: success()
@@ -222,6 +227,7 @@ jobs:
           else
              echo "Error: VERSION_FILE not found."
           fi
+
       - name: Get CI Image Name
         if: success()
         id: image-name-step
@@ -233,16 +239,16 @@ jobs:
           else
              echo "Error: IMAGE_NAME_FILE not found."
           fi
-      - name: Job Info
+
+      # https://askubuntu.com/questions/86849/how-to-unzip-a-zip-file-from-the-terminal
+      - name: unzip artifacts
         if: success()
         run: |
-          echo "pre-check is successful."
-          echo workspace is: ${{ github.workspace }}
-          echo "I'm using environment: ${{ needs.pre-check.outputs.environment-name }}"
-          echo "CI application-version is: ${{ steps.application-version-step.outputs.application-version }}"
-          echo "CI image-name is: ${{ steps.image-name-step.outputs.image-name }}"
-          echo "is workflow_dispatch event? ${{ github.event_name == 'workflow_dispatch' }}"
-          echo "is workflow_run event? ${{ github.event_name == 'workflow_run' }}"
+          unzip "artifacts/${{ vars.CATALOGS_SERVICE_NAME }}_test_artifacts/test-results.zip" -d "output"
+
+      - name: Ls Output Files
+        if: success()
+        run: ls -R ${{ github.workspace }}/output
 
   # typically release notes are published as part of the Continuous Deployment (CD) process, after the software has been built, tested, and deployed to production.
   # It's best practice to publish release notes before deploying an app to the cloud. This allows users to be informed about what changes have been made and what to expect in the latest version.
@@ -263,6 +269,7 @@ jobs:
     # https://stackoverflow.com/questions/69354003/github-action-job-fire-when-previous-job-skipped
     if: |
       always() &&
+      (needs.pre-check.result == 'success') &&
       (needs.workflow-info.result == 'success') &&
       ((github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || (github.event_name == 'workflow_dispatch' &&  github.event.inputs.should-publish-release-note == 'true'))
 
@@ -285,6 +292,7 @@ jobs:
     # https://stackoverflow.com/questions/69354003/github-action-job-fire-when-previous-job-skipped
     if: |
       always() &&
+      (needs.pre-check.result == 'success') &&
       (needs.call-release.result == 'success') &&
       ((github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || (github.event_name == 'workflow_dispatch' && github.event.inputs.should-deploy == 'true'))
 
